---
  -
    latitude: "52.986375"
    user_id: 12
    first_name: "Christina"
    second_name: "McArdle"
    longitude: "-6.043701"
  -
    latitude: "51.92893"
    user_id: 1
    first_name: "Alice"
    second_name: "Cahill"
    longitude: "-10.27699"
  -
    latitude: "51.8856167"
    user_id: 2
    first_name: "Ian"
    second_name: "McArdle"
    longitude: "-10.4240951"
  -
    latitude: "52.3191841"
    user_id: 3
    first_name: "Jack"
    second_name: "Enright"
    longitude: "-8.5072391"
  -
    latitude: "53.807778"
    user_id: 28
    first_name: "Charlie"
    second_name: "Halligan"
    longitude: "-7.714444"
  -
    latitude: "53.4692815"
    user_id: 7
    first_name: "Frank"
    second_name: "Kehoe"
    longitude: "-9.436036"
  -
    latitude: "54.0894797"
    user_id: 8
    first_name: "Eoin"
    second_name: "Ahearn"
    longitude: "-6.18671"
  -
    latitude: "53.038056"
    user_id: 26
    first_name: "Stephen"
    second_name: "McArdle"
    longitude: "-7.653889"
  -
    latitude: "54.1225"
    user_id: 27
    first_name: "Enid"
    second_name: "Gallagher"
    longitude: "-8.143333"
  -
    latitude: "53.1229599"
    user_id: 6
    first_name: "Theresa"
    second_name: "Enright"
    longitude: "-6.2705202"
  -
    latitude: "52.2559432"
    user_id: 9
    first_name: "Jack"
    second_name: "Dempsey"
    longitude: "-7.1048927"
  -
    latitude: "52.240382"
    user_id: 10
    first_name: "Georgina"
    second_name: "Gallagher"
    longitude: "-6.972413"
  -
    latitude: "53.2451022"
    user_id: 4
    first_name: "Ian"
    second_name: "Kehoe"
    longitude: "-6.238335"
  -
    latitude: "53.1302756"
    user_id: 5
    first_name: "Nora"
    second_name: "Dempsey"
    longitude: "-6.2397222"
  -
    latitude: "53.008769"
    user_id: 11
    first_name: "Richard"
    second_name: "Finnegan"
    longitude: "-6.1056711"
  -
    latitude: "53.1489345"
    user_id: 31
    first_name: "Alan"
    second_name: "Behan"
    longitude: "-6.8422408"
  -
    latitude: "53"
    user_id: 13
    first_name: "Olive"
    second_name: "Ahearn"
    longitude: "-7"
  -
    latitude: "51.999447"
    user_id: 14
    first_name: "Helen"
    second_name: "Cahill"
    longitude: "-9.742744"
  -
    latitude: "52.966"
    user_id: 15
    first_name: "Michael"
    second_name: "Ahearn"
    longitude: "-6.463"
  -
    latitude: "52.366037"
    user_id: 16
    first_name: "Ian"
    second_name: "Larkin"
    longitude: "-8.179118"
  -
    latitude: "54.180238"
    user_id: 17
    first_name: "Patricia"
    second_name: "Cahill"
    longitude: "-5.920898"
  -
    latitude: "53.0033946"
    user_id: 39
    first_name: "Lisa"
    second_name: "Ahearn"
    longitude: "-6.3877505"
  -
    latitude: "52.228056"
    user_id: 18
    first_name: "Bob"
    second_name: "Larkin"
    longitude: "-7.915833"
  -
    latitude: "54.133333"
    user_id: 24
    first_name: "Rose"
    second_name: "Enright"
    longitude: "-6.433333"
  -
    latitude: "55.033"
    user_id: 19
    first_name: "Enid"
    second_name: "Cahill"
    longitude: "-8.112"
  -
    latitude: "53.521111"
    user_id: 20
    first_name: "Enid"
    second_name: "Enright"
    longitude: "-9.831111"
  -
    latitude: "51.802"
    user_id: 21
    first_name: "David"
    second_name: "Ahearn"
    longitude: "-9.442"
  -
    latitude: "54.374208"
    user_id: 22
    first_name: "Charlie"
    second_name: "McArdle"
    longitude: "-8.371639"
  -
    latitude: "53.74452"
    user_id: 29
    first_name: "Oliver"
    second_name: "Ahearn"
    longitude: "-7.11167"
  -
    latitude: "53.761389"
    user_id: 30
    first_name: "Nick"
    second_name: "Enright"
    longitude: "-7.2875"
  -
    latitude: "54.080556"
    user_id: 23
    first_name: "Eoin"
    second_name: "Gallagher"
    longitude: "-6.361944"
  -
    latitude: "52.833502"
    user_id: 25
    first_name: "David"
    second_name: "Behan"
    longitude: "-8.522366"
