---
  -
    occassion: "Birthday party"
    invited_count: 120
    year: 2015
    month: 3
    day: 14
  -
    occassion: "Technical discussion"
    invited_count: 23
    year: 2015
    month: 4
    day: 24
  -
    occassion: "Press Release"
    invited_count: 64
    year: 2015
    month: 6
    day: 7
    cancelled: true
  -
    occassion: "New year party"
    invited_count: 55
    year: 2016
    month: 1
    day: 1
